CREATE TABLE CARTON (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    C1 INT,
    C2 INT,
    C3 INT,
    C4 INT,
    C5 INT,
    C6 INT,
    C7 INT,
    C8 INT,
    C9 INT,
    C10 INT,
    C11 INT,
    C12 INT,
    C13 INT,
    C14 INT,
    C15 INT,
    C16 INT,
    C17 INT,
    C18 INT,
    C19 INT,
    C20 INT,
    C21 INT,
    C22 INT,
    C23 INT,
    C24 INT,
    VENDIDO BOOLEAN,
    PRECIO DECIMAL(10, 2)
);

CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    DIRECCION VARCHAR(100),
    CIUDAD VARCHAR(50),
    PAIS VARCHAR(50),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    FECHA_REGISTRO DATE,
    ID_ACTIVIDAD INT
);

CREATE TABLE JUEGO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    FECHA_CREACION DATE,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR(20),
    PREMIO DECIMAL(10, 2)
);

CREATE TABLE venta (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_CARTON INT,
    ID_JUEGO INT,
    FECHA_REGISTRO DATE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_CARTON) REFERENCES CARTON(ID),
    FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID)
);

UPDATE juego j
SET j.PREMIO = (
    SELECT SUM(c.PRECIO)
    FROM carton c
    JOIN venta v ON v.ID_CARTON = c.ID
    WHERE v.ID_JUEGO = j.ID AND c.VENDIDO = 1
) / 2
WHERE j.ID = <id del juego>;


INSERT INTO `carton` (`ID`, `C1`, `C2`, `C3`, `C4`, `C5`, `C6`, `C7`, `C8`, `C9`, `C10`, `C11`, `C12`, `C13`, `C14`, `C15`, `C16`, `C17`, `C18`, `C19`, `C20`, `C21`, `C22`, `C23`, `C24`, `VENDIDO`, `PRECIO`) VALUES (NULL, '14', '11', '13', '5', '8', '16', '17', '26', '22', '30', '43', '40', '45', '36', '59', '47', '54', '49', '46', '73', '74', '66', '63', '68', '0', '2000');

SELECT SUM(c.PRECIO ) FROM carton c    JOIN venta v ON v.ID_CARTON = c.ID    WHERE v.ID_JUEGO = 1 AND c.VENDIDO = 1